services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 5s
      retries: 20

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: >
      gcloud beta emulators pubsub start
      --host-port=0.0.0.0:8085
      --project=shipments-local
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost:8085 || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 20
